# Generated by Django 3.2.16 on 2025-12-11 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentShop',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, max_length=256, null=True)),
                ('dept_code', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'department_shop',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('div_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=256, null=True)),
                ('subnet', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=16, null=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('denied', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'ip_whitelist',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=256)),
                ('section_details', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('subdepartment_id', models.AutoField(primary_key=True, serialize=False)),
                ('subdepartment_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserConsentDocReviewRemarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consent_msg', models.CharField(blank=True, max_length=512, null=True)),
                ('consent_given_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_consent_doc_review_remarks',
            },
        ),
        migrations.CreateModel(
            name='SafetyAnalysisReportCommittee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('sar_section', models.CharField(blank=True, max_length=512, null=True)),
                ('sar_section_title', models.CharField(blank=True, max_length=512, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='sar_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('npcbl_designation', models.CharField(blank=True, max_length=256, null=True)),
                ('designation', models.CharField(blank=True, max_length=256, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=16, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_executor', models.BooleanField(default=True)),
                ('access_level', models.IntegerField(default=0)),
                ('email_validation_token', models.CharField(blank=True, max_length=128, null=True)),
                ('signature', models.CharField(blank=True, max_length=256, null=True)),
                ('validation_expire_date_time', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.departmentshop')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.division')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.section')),
                ('subdepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.subdepartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.departmentshop')),
                ('div_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='divisional_head', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.division')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'committee',
            },
        ),
        migrations.CreateModel(
            name='ApprovalSignature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_hash', models.CharField(blank=True, max_length=512, null=True)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=512, null=True)),
                ('remarks_1', models.CharField(blank=True, max_length=512, null=True)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_signature',
            },
        ),
    ]
