# Generated by Django 3.2.16 on 2025-12-11 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_remove_comment_activity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 12, 11, 15, 17, 27, 297000), null=True),
        ),
    ]
