# Generated by Django 3.2.16 on 2025-12-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_alter_event_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
