# Generated by Django 3.2.16 on 2025-12-11 10:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_management', '0005_alter_event_upload_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentApprovalLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
                ('doc_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'document_approval_log',
            },
        ),
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 16, 3, 52, 774485), null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
                ('doc_id', models.CharField(blank=True, max_length=256, null=True)),
                ('access_details', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'document_log',
            },
        ),
        migrations.CreateModel(
            name='FailedLoginLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 16, 3, 52, 774485), null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
                ('login_attempt_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'failed_login_log',
            },
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 16, 3, 52, 774485), null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('access_type', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'file_log',
            },
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_header', models.TextField(blank=True, null=True)),
                ('url_target', models.CharField(blank=True, max_length=256, null=True)),
                ('notice', models.TextField(blank=True, null=True)),
                ('expire_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'notice_board',
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'password_change_log',
            },
        ),
        migrations.CreateModel(
            name='UserDeactivateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
                ('deactivation_details', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'user_deactivate_log',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 16, 3, 52, 774485), null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('message_body', models.CharField(blank=True, max_length=512, null=True)),
                ('viewed_at', models.DateTimeField(null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_log',
            },
        ),
        migrations.CreateModel(
            name='MailAndSMSLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_time', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 16, 3, 52, 774485), null=True)),
                ('phone_no', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('message_body', models.CharField(blank=True, max_length=512, null=True)),
                ('sms_success', models.BooleanField(default=False)),
                ('sms_error_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('email_error_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('email_success', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mail_sms_log',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('added_supervisor', models.TextField(blank=True, max_length=1024, null=True)),
                ('added_executor', models.TextField(blank=True, max_length=1024, null=True)),
                ('removed_supervisor', models.TextField(blank=True, max_length=1024, null=True)),
                ('removed_executor', models.TextField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('approval_level', models.IntegerField(blank=True, default=1, null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event_management.event')),
            ],
            options={
                'db_table': 'task_log',
            },
        ),
    ]
